services:
  - type: web
    name: epic-beer-run-be
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails db:migrate && bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: RAILS_SKIP_ASSET_COMPILATION
        value: "true"
